<?php

namespace App\Http\Controllers;

use App\Account;
use App\Store;
use App\User;
use Carbon\Carbon;
use GuzzleHttp\Client;
use GuzzleHttp\Exception\ClientException;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class PaypalController extends Controller
{
    public function access(Request $request)
    {
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        // $ch = curl_init();

        // curl_setopt($ch, CURLOPT_URL, 'https://api.sandbox.paypal.com/v1/oauth2/token');
        // curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        // curl_setopt($ch, CURLOPT_POST, 1);
        // curl_setopt($ch, CURLOPT_POSTFIELDS, "grant_type=client_credentials");
        // curl_setopt($ch, CURLOPT_USERPWD, 'AQC92vxvsityhXzRyjtlRCjNIm7KtW6CMNA9ZbgvjkMFooxk77HXKi0pDNi64uy4nbSlf5fVAZZFYysE' . ':' . 'EJXdCZTFxaF1t3tmnP7IMpGaEW9bfWATKB6OBw2JhyLOgM8LW4WJ-V7p90jtLghMJ_DdejV8-L4nGd7e');

        // $headers = array();
        // $headers[] = 'Accept: application/json';
        // $headers[] = 'Accept-Language: en_US';
        // $headers[] = 'Content-Type: application/x-www-form-urlencoded';
        // curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        // $result = curl_exec($ch);
        // dd($result);
        // if (curl_errno($ch)) {
        //     echo 'Error:' . curl_error($ch);
        // }
        // curl_close($ch);

        //validate inputs
        $request->validate(['paypalClientId' => 'string|required', 'paypalSecret' => 'string|required']);

        $client = new Client([
            'headers' => ['Content-Type' => 'application/x-www-form-urlencoded', 'Accept' => 'application/json'],
        ]);

        $devUrl = 'https://api.sandbox.paypal.com/v1/oauth2/token';
        $baseUrl = 'https://api.paypal.com/v1/oauth2/token';

        $paypalClientId = $request->paypalClientId;
        $paypalSecret = $request->paypalSecret;

        try {
            $res = $client->request('POST', $devUrl, [
                'auth' => [$paypalClientId, $paypalSecret],
                'form_params' => [
                    'grant_type' => 'client_credentials',
                ],
            ]);
        } catch (ClientException $e) {

            if ($e->getCode() == 401) {
                return redirect('/install/paypal')->with('error', 'Invalid cridentials');
            }

            return response()->json(['message' => 'Problem with paypal servers', 'success' => false]);
        }

        if ($res->getStatusCode() == 200) {
            $data = json_decode($res->getBody()->getContents());

            $user = Auth::user();
            $id = $user->id;
            $store = Store::find($id);
            $dt = Carbon::now();

            var_dump($id);

            $user = Account::firstOrCreate([
                'api_key' => $paypalClientId,
                'api_secret' => $paypalSecret,
                'store_id' => $id,
                'token' => $data->access_token,
                'expire_time' => $dt->addSeconds($data->expires_in),
            ]);
        }
        // dd($data);

        return redirect('/dashboard');

    }
}
