<?php

namespace App\Http\Controllers;

use App\ShopifyCharge;
use Illuminate\Http\Request;

class ShopifyChargeController extends Controller



{


    // Charge Shopify Store
    public function applyCharge()
    {
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, 'https://fulltrack.myshopify.com/admin/api/2020-01/recurring_application_charges.json');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, "{n  \"recurring_application_charge\": {n    \"name\": \"trackiny Plan\",n    \"price\": 10.0,n    \"return_url\": \"http://localhost:8000\",n    \"test\":true,n    \"trial_days\": 14n  }n}");

        $headers = array();
        $headers[] = 'Content-Type: application/json';
        $headers[] = 'X-Shopify-Access-Token: d82bc6fc69364a4eeb46ccb129bbcc9e';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

        echo json_encode($result);


    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\ShopifyCharge  $shopifyCharge
     * @return \Illuminate\Http\Response
     */
    public function show(ShopifyCharge $shopifyCharge)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\ShopifyCharge  $shopifyCharge
     * @return \Illuminate\Http\Response
     */
    public function edit(ShopifyCharge $shopifyCharge)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\ShopifyCharge  $shopifyCharge
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, ShopifyCharge $shopifyCharge)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\ShopifyCharge  $shopifyCharge
     * @return \Illuminate\Http\Response
     */
    public function destroy(ShopifyCharge $shopifyCharge)
    {
        //
    }
}
